# Generated by Django 5.2.8 on 2025-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
