# Generated by Django 5.2.8 on 2025-12-03 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'title'), name='uniq_choice_per_question'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('survey', 'title'), name='uniq_question_per_survey'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.UniqueConstraint(fields=('title',), name='uniq_survey_title'),
        ),
    ]
