# Generated by Django 5.2.5 on 2026-07-15 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_survey_uniq_survey_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('survey', 'user'), name='uniq_submission_per_user'),
        ),
    ]
